/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Contracts Api
 * Hospital Contract Management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xpikartova@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Contract
 */
export interface Contract {
    /**
     * Unique identifier of the contract
     * @type {string}
     * @memberof Contract
     */
    contractNumber: string;
    /**
     * Name of the contract
     * @type {string}
     * @memberof Contract
     */
    name: string;
    /**
     * Name of the external partner
     * @type {string}
     * @memberof Contract
     */
    partner: string;
    /**
     * Date from which the contract is valid
     * @type {Date}
     * @memberof Contract
     */
    validFrom: Date;
    /**
     * Date until which the contract is valid
     * @type {Date}
     * @memberof Contract
     */
    validUntil: Date;
    /**
     * Total budget of the contract in EUR
     * @type {number}
     * @memberof Contract
     */
    budget: number;
    /**
     * Current status of the contract
     * @type {string}
     * @memberof Contract
     */
    status: ContractStatusEnum;
    /**
     * Type of service provided under the contract
     * @type {string}
     * @memberof Contract
     */
    serviceType?: ContractServiceTypeEnum;
    /**
     * Optional description or notes about the contract
     * @type {string}
     * @memberof Contract
     */
    description?: string;
}


/**
 * @export
 */
export const ContractStatusEnum = {
    Active: 'Active',
    Ended: 'Ended',
    Archived: 'Archived'
} as const;
export type ContractStatusEnum = typeof ContractStatusEnum[keyof typeof ContractStatusEnum];

/**
 * @export
 */
export const ContractServiceTypeEnum = {
    ItSupport: 'IT Support',
    Cleaning: 'Cleaning',
    MaterialSupply: 'Material Supply',
    SecurityServices: 'Security Services',
    Other: 'Other'
} as const;
export type ContractServiceTypeEnum = typeof ContractServiceTypeEnum[keyof typeof ContractServiceTypeEnum];


/**
 * Check if a given object implements the Contract interface.
 */
export function instanceOfContract(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contractNumber" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "partner" in value;
    isInstance = isInstance && "validFrom" in value;
    isInstance = isInstance && "validUntil" in value;
    isInstance = isInstance && "budget" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function ContractFromJSON(json: any): Contract {
    return ContractFromJSONTyped(json, false);
}

export function ContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): Contract {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contractNumber': json['contractNumber'],
        'name': json['name'],
        'partner': json['partner'],
        'validFrom': (new Date(json['validFrom'])),
        'validUntil': (new Date(json['validUntil'])),
        'budget': json['budget'],
        'status': json['status'],
        'serviceType': !exists(json, 'serviceType') ? undefined : json['serviceType'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function ContractToJSON(value?: Contract | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contractNumber': value.contractNumber,
        'name': value.name,
        'partner': value.partner,
        'validFrom': (value.validFrom.toISOString().substr(0,10)),
        'validUntil': (value.validUntil.toISOString().substr(0,10)),
        'budget': value.budget,
        'status': value.status,
        'serviceType': value.serviceType,
        'description': value.description,
    };
}

