/* tslint:disable */
/* eslint-disable */
/**
 * Hospital Contracts Api
 * Hospital Contract Management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xpikartova@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Contract,
} from '../models';
import {
    ContractFromJSON,
    ContractToJSON,
} from '../models';

export interface CreateContractRequest {
    contract: Contract;
}

export interface DeleteContractRequest {
    contractId: string;
}

export interface GetContractRequest {
    contractId: string;
}

export interface UpdateContractRequest {
    contractId: string;
    contract: Contract;
}

/**
 * HospitalContractsApi - interface
 * 
 * @export
 * @interface HospitalContractsApiInterface
 */
export interface HospitalContractsApiInterface {
    /**
     * Use this method to store a new contract
     * @summary Saves new contract
     * @param {Contract} contract Contract to store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HospitalContractsApiInterface
     */
    createContractRaw(requestParameters: CreateContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Contract>>;

    /**
     * Use this method to store a new contract
     * Saves new contract
     */
    createContract(requestParameters: CreateContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Contract>;

    /**
     * Use this method to delete the specific contract
     * @summary Deletes specific contract
     * @param {string} contractId pass the id of the particular contract
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HospitalContractsApiInterface
     */
    deleteContractRaw(requestParameters: DeleteContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Use this method to delete the specific contract
     * Deletes specific contract
     */
    deleteContract(requestParameters: DeleteContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * By using contractId you get details of a specific contract
     * @summary Provides details of a single contract
     * @param {string} contractId pass the id of the particular contract
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HospitalContractsApiInterface
     */
    getContractRaw(requestParameters: GetContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Contract>>;

    /**
     * By using contractId you get details of a specific contract
     * Provides details of a single contract
     */
    getContract(requestParameters: GetContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Contract>;

    /**
     * Returns the list of all hospital contracts
     * @summary Provides the list of hospital contracts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HospitalContractsApiInterface
     */
    getContractsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Contract>>>;

    /**
     * Returns the list of all hospital contracts
     * Provides the list of hospital contracts
     */
    getContracts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Contract>>;

    /**
     * Use this method to update content of the contract
     * @summary Updates specific contract
     * @param {string} contractId pass the id of the particular contract
     * @param {Contract} contract Contract fields to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HospitalContractsApiInterface
     */
    updateContractRaw(requestParameters: UpdateContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Contract>>;

    /**
     * Use this method to update content of the contract
     * Updates specific contract
     */
    updateContract(requestParameters: UpdateContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Contract>;

}

/**
 * 
 */
export class HospitalContractsApi extends runtime.BaseAPI implements HospitalContractsApiInterface {

    /**
     * Use this method to store a new contract
     * Saves new contract
     */
    async createContractRaw(requestParameters: CreateContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Contract>> {
        if (requestParameters.contract === null || requestParameters.contract === undefined) {
            throw new runtime.RequiredError('contract','Required parameter requestParameters.contract was null or undefined when calling createContract.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/contracts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ContractToJSON(requestParameters.contract),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContractFromJSON(jsonValue));
    }

    /**
     * Use this method to store a new contract
     * Saves new contract
     */
    async createContract(requestParameters: CreateContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Contract> {
        const response = await this.createContractRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to delete the specific contract
     * Deletes specific contract
     */
    async deleteContractRaw(requestParameters: DeleteContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.contractId === null || requestParameters.contractId === undefined) {
            throw new runtime.RequiredError('contractId','Required parameter requestParameters.contractId was null or undefined when calling deleteContract.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/contracts/{contractId}`.replace(`{${"contractId"}}`, encodeURIComponent(String(requestParameters.contractId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Use this method to delete the specific contract
     * Deletes specific contract
     */
    async deleteContract(requestParameters: DeleteContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteContractRaw(requestParameters, initOverrides);
    }

    /**
     * By using contractId you get details of a specific contract
     * Provides details of a single contract
     */
    async getContractRaw(requestParameters: GetContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Contract>> {
        if (requestParameters.contractId === null || requestParameters.contractId === undefined) {
            throw new runtime.RequiredError('contractId','Required parameter requestParameters.contractId was null or undefined when calling getContract.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/contracts/{contractId}`.replace(`{${"contractId"}}`, encodeURIComponent(String(requestParameters.contractId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContractFromJSON(jsonValue));
    }

    /**
     * By using contractId you get details of a specific contract
     * Provides details of a single contract
     */
    async getContract(requestParameters: GetContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Contract> {
        const response = await this.getContractRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the list of all hospital contracts
     * Provides the list of hospital contracts
     */
    async getContractsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Contract>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/contracts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ContractFromJSON));
    }

    /**
     * Returns the list of all hospital contracts
     * Provides the list of hospital contracts
     */
    async getContracts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Contract>> {
        const response = await this.getContractsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Use this method to update content of the contract
     * Updates specific contract
     */
    async updateContractRaw(requestParameters: UpdateContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Contract>> {
        if (requestParameters.contractId === null || requestParameters.contractId === undefined) {
            throw new runtime.RequiredError('contractId','Required parameter requestParameters.contractId was null or undefined when calling updateContract.');
        }

        if (requestParameters.contract === null || requestParameters.contract === undefined) {
            throw new runtime.RequiredError('contract','Required parameter requestParameters.contract was null or undefined when calling updateContract.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/contracts/{contractId}`.replace(`{${"contractId"}}`, encodeURIComponent(String(requestParameters.contractId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ContractToJSON(requestParameters.contract),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContractFromJSON(jsonValue));
    }

    /**
     * Use this method to update content of the contract
     * Updates specific contract
     */
    async updateContract(requestParameters: UpdateContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Contract> {
        const response = await this.updateContractRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
