/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ContractList {
    }
}
declare global {
    interface HTMLContractListElement extends Components.ContractList, HTMLStencilElement {
    }
    var HTMLContractListElement: {
        prototype: HTMLContractListElement;
        new (): HTMLContractListElement;
    };
    interface HTMLElementTagNameMap {
        "contract-list": HTMLContractListElement;
    }
}
declare namespace LocalJSX {
    interface ContractList {
    }
    interface IntrinsicElements {
        "contract-list": ContractList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "contract-list": LocalJSX.IntrinsicElements["contract-list"] & JSXBase.HTMLAttributes<HTMLContractListElement>;
        }
    }
}
